# Generated by Django 4.1.5 on 2023-01-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='제목')),
                ('content', models.TextField(verbose_name='프로젝트 설명')),
                ('impression', models.TextField(verbose_name='소감')),
                ('skill', models.TextField(verbose_name='기술')),
                ('github', models.URLField()),
                ('blog', models.URLField()),
                ('demo', models.URLField()),
                ('created_at', models.CharField(max_length=15, verbose_name='날짜')),
            ],
        ),
    ]
