# Generated by Django 4.1.3 on 2022-12-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('hashtag', models.TextField()),
                ('project_name', models.TextField()),
                ('url_blog', models.TextField()),
                ('url_github', models.TextField()),
            ],
        ),
    ]
