# Generated by Django 4.1.3 on 2022-12-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Project',
        ),
    ]
