# Generated by Django 4.1.3 on 2022-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_feed_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('check_like', models.BooleanField(default=True)),
            ],
        ),
    ]
